spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://3.36.28.140:3306/protein_plus"
    username: "team7"
    password: "team7"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: local

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  server:
    port: 8081