spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://3.36.28.140:3306/protein_plus
spring.datasource.username=team7
spring.datasource.password=team7

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=local

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
